from datetime import date

from sqlalchemy import JSON, Date, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.enums import AssignmentStatus, ScheduleRunStatus, SwapStatus
from app.models.mixins import TimestampMixin, UUIDPKMixin


class SchedulingRule(Base, UUIDPKMixin, TimestampMixin):
    """Org-wide default constraints. A physician row can override the
    per-physician ones (max_consecutive_shifts, min_rest_hours,
    max_shifts_per_period); everything else here is global."""

    __tablename__ = "scheduling_rules"

    org_id: Mapped[str] = mapped_column(ForeignKey("organizations.id"), index=True, nullable=False, unique=True)

    max_consecutive_shifts: Mapped[int] = mapped_column(Integer, default=5)
    min_rest_hours: Mapped[float] = mapped_column(Float, default=10.0)
    max_nights_in_a_row: Mapped[int] = mapped_column(Integer, default=4)

    # Objective weights (relative, unit-less). Tuning these is a product
    # lever we expose to customers as a "scheduling philosophy" dial.
    weight_unfilled_shift: Mapped[float] = mapped_column(Float, default=1000.0)
    weight_fairness: Mapped[float] = mapped_column(Float, default=8.0)
    weight_preference: Mapped[float] = mapped_column(Float, default=3.0)
    weight_preferred_time_off: Mapped[float] = mapped_column(Float, default=6.0)
    weight_seniority: Mapped[float] = mapped_column(Float, default=1.0)  # 0 disables seniority skew

    extra: Mapped[dict] = mapped_column(JSON, default=dict)


class ScheduleRun(Base, UUIDPKMixin, TimestampMixin):
    """One optimizer invocation over a date range. DRAFT runs can be
    regenerated/discarded; PUBLISHED is the version of record physicians see."""

    __tablename__ = "schedule_runs"

    org_id: Mapped[str] = mapped_column(ForeignKey("organizations.id"), index=True, nullable=False)
    site_id: Mapped[str] = mapped_column(ForeignKey("sites.id"), index=True, nullable=False)
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[ScheduleRunStatus] = mapped_column(default=ScheduleRunStatus.DRAFT)

    objective_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    solver_status: Mapped[str | None] = mapped_column(String(50), nullable=True)
    solve_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    unfilled_shift_count: Mapped[int] = mapped_column(Integer, default=0)
    stats: Mapped[dict] = mapped_column(JSON, default=dict)

    # Natural-language summary generated by the AI layer (Claude), e.g.
    # "3 shifts left unfilled on Dec 24-25 due to insufficient night-eligible
    # coverage; Dr. Lee's Christmas week request was honored..."
    ai_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_by_user_id: Mapped[str | None] = mapped_column(ForeignKey("users.id"), nullable=True)

    assignments: Mapped[list["Assignment"]] = relationship(
        back_populates="schedule_run", cascade="all, delete-orphan"
    )


class Assignment(Base, UUIDPKMixin, TimestampMixin):
    """One physician assigned to one shift instance, produced by a
    ScheduleRun (or created/edited manually afterward)."""

    __tablename__ = "assignments"

    org_id: Mapped[str] = mapped_column(ForeignKey("organizations.id"), index=True, nullable=False)
    schedule_run_id: Mapped[str] = mapped_column(ForeignKey("schedule_runs.id"), index=True, nullable=False)
    shift_instance_id: Mapped[str] = mapped_column(
        ForeignKey("shift_instances.id"), index=True, nullable=False
    )
    physician_id: Mapped[str] = mapped_column(ForeignKey("physicians.id"), index=True, nullable=False)
    status: Mapped[AssignmentStatus] = mapped_column(default=AssignmentStatus.ASSIGNED)

    schedule_run: Mapped["ScheduleRun"] = relationship(back_populates="assignments")


class ShiftSwapRequest(Base, UUIDPKMixin, TimestampMixin):
    """A physician offering one of their assigned shifts to a colleague --
    either to anyone (open marketplace) or to a specific person -- pending
    scheduler approval once claimed. This is one of the most-used features
    of every incumbent scheduling product, because it's how the schedule
    actually stays correct after publish."""

    __tablename__ = "shift_swap_requests"

    org_id: Mapped[str] = mapped_column(ForeignKey("organizations.id"), index=True, nullable=False)
    assignment_id: Mapped[str] = mapped_column(ForeignKey("assignments.id"), index=True, nullable=False)
    offering_physician_id: Mapped[str] = mapped_column(ForeignKey("physicians.id"), index=True, nullable=False)
    target_physician_id: Mapped[str | None] = mapped_column(ForeignKey("physicians.id"), nullable=True)
    claimed_by_physician_id: Mapped[str | None] = mapped_column(ForeignKey("physicians.id"), nullable=True)
    status: Mapped[SwapStatus] = mapped_column(default=SwapStatus.OPEN, index=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    decided_by_user_id: Mapped[str | None] = mapped_column(ForeignKey("users.id"), nullable=True)
