"""initial schema

Revision ID: 5eacdfd1dc32
Revises: 
Create Date: 2026-09-01 14:53:40.134804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eacdfd1dc32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('physicians',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('seniority_years', sa.Float(), nullable=False),
    sa.Column('night_preference', sa.Integer(), nullable=False),
    sa.Column('weekend_preference', sa.Integer(), nullable=False),
    sa.Column('holiday_preference', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_shifts', sa.Integer(), nullable=True),
    sa.Column('min_rest_hours', sa.Float(), nullable=True),
    sa.Column('max_shifts_per_period', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.Enum('EMPLOYED', 'LOCUMS', 'CONTRACT', 'MOONLIGHTER', name='employmenttype'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('calendar_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_physicians_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physicians')),
    sa.UniqueConstraint('calendar_token', name=op.f('uq_physicians_calendar_token'))
    )
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physicians_org_id'), ['org_id'], unique=False)

    op.create_table('scheduling_rules',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('max_consecutive_shifts', sa.Integer(), nullable=False),
    sa.Column('min_rest_hours', sa.Float(), nullable=False),
    sa.Column('max_nights_in_a_row', sa.Integer(), nullable=False),
    sa.Column('weight_unfilled_shift', sa.Float(), nullable=False),
    sa.Column('weight_fairness', sa.Float(), nullable=False),
    sa.Column('weight_preference', sa.Float(), nullable=False),
    sa.Column('weight_preferred_time_off', sa.Float(), nullable=False),
    sa.Column('weight_seniority', sa.Float(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_scheduling_rules_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_rules'))
    )
    with op.batch_alter_table('scheduling_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_rules_org_id'), ['org_id'], unique=True)

    op.create_table('sites',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_sites_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_org_id'), ['org_id'], unique=False)

    op.create_table('credentials',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('credential_type', sa.Enum('STATE_LICENSE', 'DEA', 'BOARD_CERTIFICATION', 'MALPRACTICE_INSURANCE', 'ACLS', 'BLS', 'PALS', 'HOSPITAL_PRIVILEGES', 'OTHER', name='credentialtype'), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.Column('issuing_state', sa.String(length=2), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_credentials_org_id_organizations')),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_credentials_physician_id_physicians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials'))
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_physician_id'), ['physician_id'], unique=False)

    op.create_table('physician_sites',
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_physician_sites_physician_id_physicians')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_physician_sites_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physician_sites'))
    )
    with op.batch_alter_table('physician_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physician_sites_physician_id'), ['physician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physician_sites_site_id'), ['site_id'], unique=False)

    op.create_table('shift_preferences',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_shift_preferences_org_id_organizations')),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_shift_preferences_physician_id_physicians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_preferences'))
    )
    with op.batch_alter_table('shift_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_preferences_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_preferences_physician_id'), ['physician_id'], unique=False)

    op.create_table('shift_types',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('required_physicians', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_shift_types_org_id_organizations')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_shift_types_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_types'))
    )
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_types_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_types_site_id'), ['site_id'], unique=False)

    op.create_table('time_off_requests',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.Enum('VACATION', 'CME', 'PERSONAL', 'SICK', 'OTHER', name='timeofftype'), nullable=False),
    sa.Column('priority', sa.Enum('MUST', 'PREFERRED', name='requestpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'WITHDRAWN', name='requeststatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_time_off_requests_org_id_organizations')),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_time_off_requests_physician_id_physicians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_requests'))
    )
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_requests_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_physician_id'), ['physician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SCHEDULER', 'PHYSICIAN', name='userrole'), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_users_physician_id_physicians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_logs_org_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)

    op.create_table('oauth_identities',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_oauth_identity_subject')
    )
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_identities_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_runs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='schedulerunstatus'), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('solve_seconds', sa.Float(), nullable=True),
    sa.Column('unfilled_shift_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_schedule_runs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_schedule_runs_org_id_organizations')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_schedule_runs_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_runs'))
    )
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_runs_site_id'), ['site_id'], unique=False)

    op.create_table('shift_instances',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('shift_type_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_run_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('required_physicians', sa.Integer(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_shift_instances_org_id_organizations')),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], name=op.f('fk_shift_instances_schedule_run_id_schedule_runs')),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], name=op.f('fk_shift_instances_shift_type_id_shift_types')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_shift_instances_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_instances'))
    )
    with op.batch_alter_table('shift_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_instances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_instances_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_instances_schedule_run_id'), ['schedule_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_instances_shift_type_id'), ['shift_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_instances_site_id'), ['site_id'], unique=False)

    op.create_table('assignments',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_run_id', sa.String(length=36), nullable=False),
    sa.Column('shift_instance_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'SWAPPED', 'DROPPED', name='assignmentstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assignments_org_id_organizations')),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], name=op.f('fk_assignments_physician_id_physicians')),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], name=op.f('fk_assignments_schedule_run_id_schedule_runs')),
    sa.ForeignKeyConstraint(['shift_instance_id'], ['shift_instances.id'], name=op.f('fk_assignments_shift_instance_id_shift_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_physician_id'), ['physician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_schedule_run_id'), ['schedule_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_shift_instance_id'), ['shift_instance_id'], unique=False)

    op.create_table('shift_swap_requests',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('offering_physician_id', sa.String(length=36), nullable=False),
    sa.Column('target_physician_id', sa.String(length=36), nullable=True),
    sa.Column('claimed_by_physician_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'APPROVED', 'REJECTED', 'CANCELLED', name='swapstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_shift_swap_requests_assignment_id_assignments')),
    sa.ForeignKeyConstraint(['claimed_by_physician_id'], ['physicians.id'], name=op.f('fk_shift_swap_requests_claimed_by_physician_id_physicians')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_shift_swap_requests_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['offering_physician_id'], ['physicians.id'], name=op.f('fk_shift_swap_requests_offering_physician_id_physicians')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_shift_swap_requests_org_id_organizations')),
    sa.ForeignKeyConstraint(['target_physician_id'], ['physicians.id'], name=op.f('fk_shift_swap_requests_target_physician_id_physicians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_swap_requests'))
    )
    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_offering_physician_id'), ['offering_physician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_status'))
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_offering_physician_id'))
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_assignment_id'))

    op.drop_table('shift_swap_requests')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_shift_instance_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_schedule_run_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_physician_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_org_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('shift_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_instances_site_id'))
        batch_op.drop_index(batch_op.f('ix_shift_instances_shift_type_id'))
        batch_op.drop_index(batch_op.f('ix_shift_instances_schedule_run_id'))
        batch_op.drop_index(batch_op.f('ix_shift_instances_org_id'))
        batch_op.drop_index(batch_op.f('ix_shift_instances_date'))

    op.drop_table('shift_instances')
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_runs_site_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_runs_org_id'))

    op.drop_table('schedule_runs')
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_identities_user_id'))

    op.drop_table('oauth_identities')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_requests_status'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_physician_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_org_id'))

    op.drop_table('time_off_requests')
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_types_site_id'))
        batch_op.drop_index(batch_op.f('ix_shift_types_org_id'))

    op.drop_table('shift_types')
    with op.batch_alter_table('shift_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_preferences_physician_id'))
        batch_op.drop_index(batch_op.f('ix_shift_preferences_org_id'))

    op.drop_table('shift_preferences')
    with op.batch_alter_table('physician_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physician_sites_site_id'))
        batch_op.drop_index(batch_op.f('ix_physician_sites_physician_id'))

    op.drop_table('physician_sites')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_physician_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_org_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_org_id'))

    op.drop_table('sites')
    with op.batch_alter_table('scheduling_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_rules_org_id'))

    op.drop_table('scheduling_rules')
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physicians_org_id'))

    op.drop_table('physicians')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
