"""initial schema

Revision ID: d00230338b2d
Revises: 
Create Date: 2026-09-01 14:40:13.503474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00230338b2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('physicians',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('seniority_years', sa.Float(), nullable=False),
    sa.Column('night_preference', sa.Integer(), nullable=False),
    sa.Column('weekend_preference', sa.Integer(), nullable=False),
    sa.Column('holiday_preference', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_shifts', sa.Integer(), nullable=True),
    sa.Column('min_rest_hours', sa.Float(), nullable=True),
    sa.Column('max_shifts_per_period', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physicians_org_id'), 'physicians', ['org_id'], unique=False)
    op.create_table('scheduling_rules',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('max_consecutive_shifts', sa.Integer(), nullable=False),
    sa.Column('min_rest_hours', sa.Float(), nullable=False),
    sa.Column('max_nights_in_a_row', sa.Integer(), nullable=False),
    sa.Column('weight_unfilled_shift', sa.Float(), nullable=False),
    sa.Column('weight_fairness', sa.Float(), nullable=False),
    sa.Column('weight_preference', sa.Float(), nullable=False),
    sa.Column('weight_preferred_time_off', sa.Float(), nullable=False),
    sa.Column('weight_seniority', sa.Float(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_rules_org_id'), 'scheduling_rules', ['org_id'], unique=True)
    op.create_table('sites',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_org_id'), 'sites', ['org_id'], unique=False)
    op.create_table('physician_sites',
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physician_sites_physician_id'), 'physician_sites', ['physician_id'], unique=False)
    op.create_index(op.f('ix_physician_sites_site_id'), 'physician_sites', ['site_id'], unique=False)
    op.create_table('shift_preferences',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_preferences_org_id'), 'shift_preferences', ['org_id'], unique=False)
    op.create_index(op.f('ix_shift_preferences_physician_id'), 'shift_preferences', ['physician_id'], unique=False)
    op.create_table('shift_types',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('required_physicians', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_types_org_id'), 'shift_types', ['org_id'], unique=False)
    op.create_index(op.f('ix_shift_types_site_id'), 'shift_types', ['site_id'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.Enum('VACATION', 'CME', 'PERSONAL', 'SICK', 'OTHER', name='timeofftype'), nullable=False),
    sa.Column('priority', sa.Enum('MUST', 'PREFERRED', name='requestpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'WITHDRAWN', name='requeststatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_org_id'), 'time_off_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_physician_id'), 'time_off_requests', ['physician_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_status'), 'time_off_requests', ['status'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SCHEDULER', 'PHYSICIAN', name='userrole'), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('schedule_runs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='schedulerunstatus'), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('solve_seconds', sa.Float(), nullable=True),
    sa.Column('unfilled_shift_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_runs_org_id'), 'schedule_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_schedule_runs_site_id'), 'schedule_runs', ['site_id'], unique=False)
    op.create_table('shift_instances',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('shift_type_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_run_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('DAY', 'NIGHT', 'SWING', 'ADMIN', name='shiftcategory'), nullable=False),
    sa.Column('required_physicians', sa.Integer(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_instances_date'), 'shift_instances', ['date'], unique=False)
    op.create_index(op.f('ix_shift_instances_org_id'), 'shift_instances', ['org_id'], unique=False)
    op.create_index(op.f('ix_shift_instances_schedule_run_id'), 'shift_instances', ['schedule_run_id'], unique=False)
    op.create_index(op.f('ix_shift_instances_shift_type_id'), 'shift_instances', ['shift_type_id'], unique=False)
    op.create_index(op.f('ix_shift_instances_site_id'), 'shift_instances', ['site_id'], unique=False)
    op.create_table('assignments',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_run_id', sa.String(length=36), nullable=False),
    sa.Column('shift_instance_id', sa.String(length=36), nullable=False),
    sa.Column('physician_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'SWAPPED', 'DROPPED', name='assignmentstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], ),
    sa.ForeignKeyConstraint(['shift_instance_id'], ['shift_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_org_id'), 'assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_assignments_physician_id'), 'assignments', ['physician_id'], unique=False)
    op.create_index(op.f('ix_assignments_schedule_run_id'), 'assignments', ['schedule_run_id'], unique=False)
    op.create_index(op.f('ix_assignments_shift_instance_id'), 'assignments', ['shift_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_shift_instance_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_schedule_run_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_physician_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_org_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_shift_instances_site_id'), table_name='shift_instances')
    op.drop_index(op.f('ix_shift_instances_shift_type_id'), table_name='shift_instances')
    op.drop_index(op.f('ix_shift_instances_schedule_run_id'), table_name='shift_instances')
    op.drop_index(op.f('ix_shift_instances_org_id'), table_name='shift_instances')
    op.drop_index(op.f('ix_shift_instances_date'), table_name='shift_instances')
    op.drop_table('shift_instances')
    op.drop_index(op.f('ix_schedule_runs_site_id'), table_name='schedule_runs')
    op.drop_index(op.f('ix_schedule_runs_org_id'), table_name='schedule_runs')
    op.drop_table('schedule_runs')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_off_requests_status'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_physician_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_org_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_shift_types_site_id'), table_name='shift_types')
    op.drop_index(op.f('ix_shift_types_org_id'), table_name='shift_types')
    op.drop_table('shift_types')
    op.drop_index(op.f('ix_shift_preferences_physician_id'), table_name='shift_preferences')
    op.drop_index(op.f('ix_shift_preferences_org_id'), table_name='shift_preferences')
    op.drop_table('shift_preferences')
    op.drop_index(op.f('ix_physician_sites_site_id'), table_name='physician_sites')
    op.drop_index(op.f('ix_physician_sites_physician_id'), table_name='physician_sites')
    op.drop_table('physician_sites')
    op.drop_index(op.f('ix_sites_org_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_scheduling_rules_org_id'), table_name='scheduling_rules')
    op.drop_table('scheduling_rules')
    op.drop_index(op.f('ix_physicians_org_id'), table_name='physicians')
    op.drop_table('physicians')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
